import { Link } from 'react-router-dom'
import { useEffect } from 'react'

type Service = { slug: string; eyebrow: string; title: string; intro: string; problem: string; outcomes: string[]; capabilities: string[]; next: string }

const services: Record<string, Service> = {
  performance: { slug: 'performance', eyebrow: 'Performance engineering', title: 'Make important pages faster for real people.', intro: 'Performance work starts with evidence: where bytes, network delay, rendering work and interaction cost are actually coming from.', problem: 'Slow experiences are rarely caused by one number. Ottimo helps separate the measurable bottleneck from assumptions, then focuses effort on the pages and journeys that matter.', outcomes: ['A clearer view of page weight and rendering cost', 'Prioritised performance opportunities', 'Comparable evidence for verifying improvements'], capabilities: ['Resource and asset analysis', 'Rendering and main-thread signals', 'Performance score history', 'Before-and-after audit comparison'], next: '/app/performance' },
  seo: { slug: 'seo', eyebrow: 'Search visibility', title: 'Help search systems understand what matters.', intro: 'Technical SEO should make the important parts of a website discoverable, understandable and structurally trustworthy without promising rankings that the evidence cannot support.', problem: 'Search visibility depends on many systems outside an audit. Ottimo therefore separates observed technical SEO evidence from traffic, ranking and conversion outcomes.', outcomes: ['Clearer crawl and indexing signals', 'Page and content structure evidence', 'Search observations kept separate from audit findings'], capabilities: ['Sitemaps and canonical signals', 'Robots and crawl-path analysis', 'Metadata and semantic structure', 'Search Console integration boundary'], next: '/app/seo' },
  accessibility: { slug: 'accessibility', eyebrow: 'Accessibility', title: 'Build journeys more people can use.', intro: 'Accessibility is part of product quality. Ottimo turns structural and interaction findings into work that can be implemented and verified.', problem: 'A page can look correct while still being difficult to navigate, understand or operate. Accessibility evidence needs to cover structure, names, focus and interaction—not just a score.', outcomes: ['Clearer accessibility findings', 'Evidence attached to affected content or controls', 'Repeatable verification after fixes'], capabilities: ['Semantic structure checks', 'Keyboard and focus evidence', 'Accessible-name and content signals', 'Accessibility history'], next: '/app/accessibility' },
  usability: { slug: 'usability', eyebrow: 'Experience', title: 'Remove friction from the journeys that matter.', intro: 'Good usability makes the next step obvious. Ottimo connects page structure, content clarity and interaction signals so teams can see where a journey becomes harder than it needs to be.', problem: 'Usability is broader than conversion optimisation. Ottimo avoids claiming that a single audit finding caused a business outcome and instead gives teams evidence they can investigate.', outcomes: ['Visible journey friction', 'Clearer content and interaction findings', 'A shared language between product and engineering'], capabilities: ['Content and hierarchy signals', 'Navigation and interaction findings', 'Evidence-backed recommendations', 'Action and verification workflow'], next: '/app/usability' },
  technical: { slug: 'technical', eyebrow: 'Technical quality', title: 'Make the foundations dependable.', intro: 'Technical quality is the layer beneath the experience: crawlability, resources, security signals, structure and implementation choices that can create downstream problems.', problem: 'Technical debt becomes expensive when nobody can see its customer-facing impact. Ottimo connects technical observations to affected pages and prioritised work.', outcomes: ['A clearer technical risk surface', 'Evidence attached to concrete findings', 'Prioritised engineering work'], capabilities: ['Technical site signals', 'Security and reliability checks', 'Resource and page diagnostics', 'Action prioritisation'], next: '/app/technical' },
  ai: { slug: 'ai', eyebrow: 'AI readiness', title: 'Make your website useful to people and machines.', intro: 'AI readiness begins with good information architecture, authoritative content and machine-readable context. AI should amplify those foundations rather than hide weak ones.', problem: 'Adding an AI feature does not make a website AI-ready. Ottimo focuses on the underlying knowledge, structure and evidence that future interfaces need to work with confidently.', outcomes: ['Clearer authoritative information', 'Stronger machine-readable context', 'Responsible AI guidance grounded in evidence'], capabilities: ['Structured information signals', 'Content and page identity evidence', 'AI-readiness audit category', 'Evidence-grounded AI guidance'], next: '/app/ai' },
}

function Metadata({ service }: { service: Service }) { useEffect(() => { document.title = service.title + ' — Ottimo'; const description = document.querySelector<HTMLMetaElement>('meta[name="description"]'); if (description) description.content = service.intro }, [service]); return null }

export function PublicServicePage({ slug }: { slug: string }) {
  const service = services[slug] ?? services.performance
  return <div className="public-service-page">
    <Metadata service={service} />
    <section className="service-hero"><span className="eyebrow">{service.eyebrow}</span><h1>{service.title}</h1><p>{service.intro}</p><div className="hero-actions"><Link className="btn btn-primary" to="/#start">Analyse my website</Link><Link className="text-link" to="/methodology">See our methodology →</Link></div></section>
    <section className="service-problem"><div><span className="eyebrow">Why it matters</span><h2>Start with the signal, not the story.</h2></div><p>{service.problem}</p></section>
    <section className="service-detail-grid"><div><span className="eyebrow">What you can work toward</span><h2>Useful outcomes, not vanity metrics.</h2><ul>{service.outcomes.map(outcome => <li key={outcome}>{outcome}</li>)}</ul></div><div><span className="eyebrow">Ottimo capability</span><h2>What the platform supports.</h2><ul>{service.capabilities.map(capability => <li key={capability}>{capability}</li>)}</ul></div></section>
    <section className="service-proof"><span className="eyebrow">Evidence standard</span><h2>Observed findings stay distinct from inference.</h2><p>Ottimo can tell you what it measured, what it inferred and what remains unavailable. That distinction carries through recommendations, integrations, longitudinal history and verification.</p><Link className="text-link" to={service.next}>Explore {service.eyebrow.toLowerCase()} in the platform →</Link></section>
    <section className="callout"><span className="eyebrow">Start with your website</span><h2>Find the next useful improvement.</h2><p>Run an audit, inspect the evidence and decide what deserves attention first.</p><Link className="btn btn-primary" to="/app/audits/new">Start a demo audit</Link></section>
  </div>
}