import { chromium, type Browser } from 'playwright'
import { assertPublicTarget } from './security'
import type { AuditRequest, PageSnapshot, ResourceSnapshot } from './types'
const MAX_HTML_BYTES=5*1024*1024
const MAX_RESOURCES=500
const USER_AGENT='OttimoAuditEngine/0.1 (+https://ottimo-site.netlify.app/)'
export interface PageCollector{collect(request:AuditRequest):Promise<PageSnapshot>}
export class PlaywrightPageCollector implements PageCollector{
 async collect(request:AuditRequest){const target=await assertPublicTarget(request.url);const browser:Browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:request.viewport??{width:1365,height:900},userAgent:USER_AGENT});const resources=new Map<string,ResourceSnapshot>();const failures:Array<{url:string;errorText:string}>=[];const redirects=[target.href]
 page.on('response',r=>{if(resources.size>=MAX_RESOURCES)return;const type=r.request().resourceType();if(type==='document'&&!redirects.includes(r.url()))redirects.push(r.url());resources.set(r.url(),{url:r.url(),type,status:r.status(),contentType:r.headers()['content-type']})})
 page.on('requestfailed',r=>failures.push({url:r.url(),errorText:r.failure()?.errorText??'Unknown network failure'}))
 try{const response=await page.goto(target.href,{waitUntil:'networkidle',timeout:request.timeoutMs??30000});if(!response)throw new Error('The browser did not receive a document response.');const html=await page.content();if(Buffer.byteLength(html,'utf8')>MAX_HTML_BYTES)throw new Error('The target HTML exceeds the collection limit.');const timing=await page.evaluate(()=>{const nav=performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming|undefined;const paint=performance.getEntriesByName('first-contentful-paint')[0];return{dnsMs:nav?nav.domainLookupEnd-nav.domainLookupStart:undefined,connectionMs:nav?nav.connectEnd-nav.connectStart:undefined,requestMs:nav?nav.responseEnd-nav.requestStart:undefined,ttfbMs:nav?nav.responseStart-nav.requestStart:undefined,domContentLoadedMs:nav?.domContentLoadedEventEnd,loadMs:nav?.loadEventEnd,fcpMs:paint?.startTime,transferSize:nav?.transferSize,encodedBodySize:nav?.encodedBodySize,decodedBodySize:nav?.decodedBodySize}});const metadata=await page.evaluate(()=>({title:document.title.trim(),language:document.documentElement.lang||undefined,secureContext:window.isSecureContext}));const accessibility=await page.evaluate(()=>({violations:[]} as PageSnapshot['accessibility']));const result={requestedUrl:target.href,finalUrl:page.url(),status:response.status(),statusText:response.statusText(),contentType:response.headers()['content-type']??'',redirectChain:redirects,html,title:metadata.title,language:metadata.language,secureContext:metadata.secureContext,timing,resources:[...resources.values()],requestFailures:failures,accessibility};await browser.close();return result}catch(error){await browser.close();throw error}}
}
